services:
  cbtw.api:
    image: cbtw.api
    ports:
      - "5299:8080"
    build:
      context: .
      dockerfile: CBTW.API/Dockerfile

  cbtw.api.gateway:
    image: cbtw.api.gateway
    ports:
      - "5135:8080"
    build:
      context: .
      dockerfile: CBTW.API.Gateway/Dockerfile
    links:
      - cbtw.api
