# This is a generated file. Not intended for manual editing.
services:
  cbtw.api:
    build:
      context: "/mnt/dev/CBTW/CBTW_TechTest"
      dockerfile: "CBTW.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/CBTW.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "cbtw.api:dev"
    ports: []
    volumes:
    - "/mnt/dev/CBTW/CBTW_TechTest/CBTW.API:/app:rw"
    - "/mnt/dev/CBTW/CBTW_TechTest:/src:rw"
    - "/root/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
  cbtw.api.gateway:
    build:
      context: "/mnt/dev/CBTW/CBTW_TechTest"
      dockerfile: "CBTW.API.Gateway/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/CBTW.API.Gateway.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "cbtw.api.gateway:dev"
    ports: []
    volumes:
    - "/mnt/dev/CBTW/CBTW_TechTest/CBTW.API.Gateway:/app:rw"
    - "/mnt/dev/CBTW/CBTW_TechTest:/src:rw"
    - "/root/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
