# This is a generated file. Not intended for manual editing.
services:
  cbtw.api:
    build:
      context: "/mnt/dev/CBTW/CBTW_TechTest"
      dockerfile: "CBTW.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57410"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "cbtw.api:dev"
    ports:
    - "127.0.0.1:57010:57000"
    - "127.0.0.1:57210:57200"
    - "127.0.0.1:57410:57410"
    volumes:
    - "/mnt/dev/CBTW/CBTW_TechTest/CBTW.API:/app:rw"
    - "/mnt/dev/CBTW/CBTW_TechTest:/src:rw"
    - "/root/.nuget/packages:/home/app/.nuget/packages"
    - "/root/.local/share/JetBrains/RiderRemoteDebugger/2025.3.1/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/home/shg/.jetbrains/rider/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/root/.cache/JetBrains/Rider2025.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2026_1_28_15_56_21:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  cbtw.api.gateway:
    build:
      context: "/mnt/dev/CBTW/CBTW_TechTest"
      dockerfile: "CBTW.API.Gateway/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57411"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "cbtw.api.gateway:dev"
    ports:
    - "127.0.0.1:57011:57000"
    - "127.0.0.1:57211:57200"
    - "127.0.0.1:57411:57411"
    volumes:
    - "/mnt/dev/CBTW/CBTW_TechTest/CBTW.API.Gateway:/app:rw"
    - "/mnt/dev/CBTW/CBTW_TechTest:/src:rw"
    - "/root/.nuget/packages:/home/app/.nuget/packages"
    - "/root/.local/share/JetBrains/RiderRemoteDebugger/2025.3.1/Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "/home/shg/.jetbrains/rider/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/root/.cache/JetBrains/Rider2025.3/log/DebuggerWorker/JetBrains.Debugger.Worker.2026_1_28_15_56_21:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
